# Containerizes your app:

#     dockerfile
#     Copy
#     Edit
#     FROM python:3.10-slim
    
#     WORKDIR /app
    
#     COPY requirements.txt .
#     RUN pip install --no-cache-dir -r requirements.txt
    
#     COPY . .
    
#     CMD ["python", "manage.py"]